apiVersion: v1
kind: ConfigMap
metadata:
  name: fault-config-frontend
  namespace: target-system
data:
  FAULT_MODE: none #modes are none, crash, log_spam, error_burst
  BACKEND_URL: "http://backend:5000"
