apiVersion: v1
kind: ServiceAccount
metadata:
  name: log-parser
  namespace: monitoring-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: log-parser
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: log-parser
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: log-parser
subjects:
  - kind: ServiceAccount
    name: log-parser
    namespace: monitoring-system