apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: target-system
spec:
  selector:
    name: target-system-worker-deploy
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
